/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.innominds.portlets.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the NapierUser service. Represents a row in the &quot;NH_NapierUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.innominds.portlets.service.model.impl.NapierUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.innominds.portlets.service.model.impl.NapierUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NapierUser
 * @see com.innominds.portlets.service.model.impl.NapierUserImpl
 * @see com.innominds.portlets.service.model.impl.NapierUserModelImpl
 * @generated
 */
public interface NapierUserModel extends BaseModel<NapierUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a napier user model instance should use the {@link NapierUser} interface instead.
	 */

	/**
	 * Returns the primary key of this napier user.
	 *
	 * @return the primary key of this napier user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this napier user.
	 *
	 * @param primaryKey the primary key of this napier user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this napier user.
	 *
	 * @return the uuid of this napier user
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this napier user.
	 *
	 * @param uuid the uuid of this napier user
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this napier user.
	 *
	 * @return the ID of this napier user
	 */
	public long getId();

	/**
	 * Sets the ID of this napier user.
	 *
	 * @param id the ID of this napier user
	 */
	public void setId(long id);

	/**
	 * Returns the liferay user ID of this napier user.
	 *
	 * @return the liferay user ID of this napier user
	 */
	@AutoEscape
	public String getLiferayUserId();

	/**
	 * Sets the liferay user ID of this napier user.
	 *
	 * @param liferayUserId the liferay user ID of this napier user
	 */
	public void setLiferayUserId(String liferayUserId);

	/**
	 * Returns the user type of this napier user.
	 *
	 * @return the user type of this napier user
	 */
	@AutoEscape
	public String getUserType();

	/**
	 * Sets the user type of this napier user.
	 *
	 * @param userType the user type of this napier user
	 */
	public void setUserType(String userType);

	/**
	 * Returns the mr number of this napier user.
	 *
	 * @return the mr number of this napier user
	 */
	@AutoEscape
	public String getMrNumber();

	/**
	 * Sets the mr number of this napier user.
	 *
	 * @param mrNumber the mr number of this napier user
	 */
	public void setMrNumber(String mrNumber);

	/**
	 * Returns the tpa ID of this napier user.
	 *
	 * @return the tpa ID of this napier user
	 */
	@AutoEscape
	public String getTpaId();

	/**
	 * Sets the tpa ID of this napier user.
	 *
	 * @param tpaId the tpa ID of this napier user
	 */
	public void setTpaId(String tpaId);

	/**
	 * Returns the coroporate ID of this napier user.
	 *
	 * @return the coroporate ID of this napier user
	 */
	@AutoEscape
	public String getCoroporateId();

	/**
	 * Sets the coroporate ID of this napier user.
	 *
	 * @param coroporateId the coroporate ID of this napier user
	 */
	public void setCoroporateId(String coroporateId);

	/**
	 * Returns the patient ID of this napier user.
	 *
	 * @return the patient ID of this napier user
	 */
	@AutoEscape
	public String getPatientId();

	/**
	 * Sets the patient ID of this napier user.
	 *
	 * @param patientId the patient ID of this napier user
	 */
	public void setPatientId(String patientId);

	/**
	 * Returns the age of this napier user.
	 *
	 * @return the age of this napier user
	 */
	public int getAge();

	/**
	 * Sets the age of this napier user.
	 *
	 * @param age the age of this napier user
	 */
	public void setAge(int age);

	/**
	 * Returns the mobile of this napier user.
	 *
	 * @return the mobile of this napier user
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this napier user.
	 *
	 * @param mobile the mobile of this napier user
	 */
	public void setMobile(String mobile);

	/**
	 * Returns the gender of this napier user.
	 *
	 * @return the gender of this napier user
	 */
	@AutoEscape
	public String getGender();

	/**
	 * Sets the gender of this napier user.
	 *
	 * @param gender the gender of this napier user
	 */
	public void setGender(String gender);

	/**
	 * Returns the address of this napier user.
	 *
	 * @return the address of this napier user
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this napier user.
	 *
	 * @param address the address of this napier user
	 */
	public void setAddress(String address);

	/**
	 * Returns the specialization of this napier user.
	 *
	 * @return the specialization of this napier user
	 */
	@AutoEscape
	public String getSpecialization();

	/**
	 * Sets the specialization of this napier user.
	 *
	 * @param specialization the specialization of this napier user
	 */
	public void setSpecialization(String specialization);

	/**
	 * Returns the firstname of this napier user.
	 *
	 * @return the firstname of this napier user
	 */
	@AutoEscape
	public String getFirstname();

	/**
	 * Sets the firstname of this napier user.
	 *
	 * @param firstname the firstname of this napier user
	 */
	public void setFirstname(String firstname);

	/**
	 * Returns the lastname of this napier user.
	 *
	 * @return the lastname of this napier user
	 */
	@AutoEscape
	public String getLastname();

	/**
	 * Sets the lastname of this napier user.
	 *
	 * @param lastname the lastname of this napier user
	 */
	public void setLastname(String lastname);

	/**
	 * Returns the username of this napier user.
	 *
	 * @return the username of this napier user
	 */
	@AutoEscape
	public String getUsername();

	/**
	 * Sets the username of this napier user.
	 *
	 * @param username the username of this napier user
	 */
	public void setUsername(String username);

	/**
	 * Returns the password of this napier user.
	 *
	 * @return the password of this napier user
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this napier user.
	 *
	 * @param password the password of this napier user
	 */
	public void setPassword(String password);

	/**
	 * Returns the email of this napier user.
	 *
	 * @return the email of this napier user
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this napier user.
	 *
	 * @param email the email of this napier user
	 */
	public void setEmail(String email);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(NapierUser napierUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<NapierUser> toCacheModel();

	@Override
	public NapierUser toEscapedModel();

	@Override
	public NapierUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}