/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.innominds.portlets.service.model.impl;

import com.innominds.portlets.service.model.NapierUser;
import com.innominds.portlets.service.service.NapierUserLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the NapierUser service. Represents a row in the &quot;NH_NapierUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NapierUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NapierUserImpl
 * @see com.innominds.portlets.service.model.NapierUser
 * @generated
 */
public abstract class NapierUserBaseImpl extends NapierUserModelImpl
	implements NapierUser {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a napier user model instance should use the {@link NapierUser} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			NapierUserLocalServiceUtil.addNapierUser(this);
		}
		else {
			NapierUserLocalServiceUtil.updateNapierUser(this);
		}
	}
}